swagger: "2.0"
info:
  version: "0.0.1"
  title: Smartmap Analytics
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-volos-resources: {}
paths:
  /yp/search/geocode:
    x-swagger-router-controller: perform_search
    x-volos-authorizations: {}
    x-volos-apply: {}
    get:
      description: Returns geocode result given a free form address
      operationId: performSearch
      parameters:
        - name: freeFormAddress
          in: query
          description: The address to geocode
          required: true
          type: string
        - name: limit
          in: query
          description: The maximum number of results to display
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeocodeResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /yp/search/reverse:
    x-swagger-router-controller: reverse_geocode
    x-volos-authorizations: {}
    x-volos-apply: {}
    get:
      description: Returns geocode result given a coordinate
      operationId: reverseGeocode
      parameters:
        - name: lat
          in: query
          description: The latitude of the point
          required: true
          type: number
          format: double
        - name: lng
          in: query
          description: The longitude of the point
          required: true
          type: number
          format: double
        - name: radius
          in: query
          description: The maximum distance covered from the centre point
          type: number
        - name: limit
          in: query
          description: The maximum number of results to display
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ReverseResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  GeocodeResponse:
    required:
      - message
    properties:
      message:
        type: string
  ReverseResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
